theme: minima
title: Sam Ewert's Programming Projects
author: Sam Ewert
description: The culmination of all the programming projects I have created since 2018 when I was in high school. Configure file!!!
